#!/bin/bash

#custom app stub generator

#define parameters
NAME=$1

#define template
cat << _EOF_
/*global Ext */

//enable Ext.Loader & turn off cache busting
Ext.Loader.setConfig({
    enabled: true,
    disableCaching: false
});

//set path for all $NAME.* classes
Ext.Loader.setPath({
    '$NAME': 'app'
});

//create an application
Ext.application({
    name: '$NAME'
});
_EOF_